name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What feature do you want?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve?

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - frontend
        - backend
